### ISSUE TITLE
No module named 'keyring' after clean installation

### ISSUE THREAD

**Issue by jkornblum** [conda-forge/snowflake-connector-python-feedstock#5]
Issue: Import error after clean installation.

In a new environment I run a validation script (from Snowflake docs) but get a module import error. I think there is a dependency not defined in this feedstock.

```
create env -n snowflake python=3.6
conda activate snowflake
conda install -c conda-forge snowflake-connector-python
python validate.py
```

This is the stacktrace
```
Traceback (most recent call last):
  File "Documents/validate.py", line 2, in <module>
    import snowflake.connector
  File "/home/jk88/miniconda3/envs/snowflake/lib/python3.6/site-packages/snowflake/connector/__init__.py", line 21, in <module>
    from .connection import SnowflakeConnection
  File "/home/jk88/miniconda3/envs/snowflake/lib/python3.6/site-packages/snowflake/connector/connection.py", line 18, in <module>
    from .auth import Auth
  File "/home/jk88/miniconda3/envs/snowflake/lib/python3.6/site-packages/snowflake/connector/auth.py", line 20, in <module>
    import keyring
ModuleNotFoundError: No module named 'keyring'
```
validate.py
```
#!/usr/bin/env python
import snowflake.connector

# Gets the version
ctx = snowflake.connector.connect(
    user='username',
    password='password',
    account='account'
    )
cs = ctx.cursor()
try:
    cs.execute("SELECT current_version()")
    one_row = cs.fetchone()
    print(one_row[0])
finally:	
    cs.close()
ctx.close()
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/jk88/miniconda3/envs/snowflake:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py36_1003    conda-forge
azure-common              1.1.16                     py_0    conda-forge
azure-nspkg               2.0.0                      py_1    conda-forge
azure-storage             0.36.0                py36_1000    conda-forge
boto3                     1.9.80                     py_0    conda-forge
botocore                  1.12.80                    py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5          py36h9745a5d_1001    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cryptography              2.3.1           py36hb7f436b_1000    conda-forge
docutils                  0.14                  py36_1001    conda-forge
future                    0.17.1                py36_1000    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
ijson                     2.3                        py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
pip                       18.1                  py36_1000    conda-forge
pycparser                 2.19                       py_0    conda-forge
pycryptodomex             3.7.2           py36h14c3975_1000    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.7             hd21baee_1001    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py36_1000    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
snowflake-connector-python 1.7.3                    py36_0    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : snowflake
    active env location : /home/jk88/miniconda3/envs/snowflake
            shell level : 2
       user config file : /home/jk88/.condarc
 populated config files : /home/jk88/.condarc
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/jk88/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/jk88/miniconda3/pkgs
                          /home/jk88/.conda/pkgs
       envs directories : /home/jk88/miniconda3/envs
                          /home/jk88/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.15.0-43-generic elementary/5.0 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by hajapy** [comment]
This is an optional dependency: https://github.com/snowflakedb/snowflake-connector-python/blob/v1.8.4/setup.py#L84

Is it still important to you?
